version: '3.8'

services:
  app:
    build: .
    container_name: mongolgpt-backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/gpt-data-collector
    depends_on:
      - mongodb
    networks:
      - mongolgpt-network
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongolgpt-network
    restart: always

networks:
  mongolgpt-network:
    driver: bridge

volumes:
  mongodb_data: