version: '3.8'

services:
  frontend:
    build: .
    container_name: mongolgpt-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - mongolgpt-frontend-network
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  mongolgpt-frontend-network:
    driver: bridge